/*******************************************************************************
 * @file callback.c
 * @brief USB Callbacks.
 *******************************************************************************/

//=============================================================================
// src/callback.c: generated by Hardware Configurator
//
// This file is only generated if it does not exist. Modifications in this file
// will persist even if Configurator generates code. To refresh this file,
// you must first delete it and then regenerate code.
//=============================================================================
//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB2_Register_Enums.h>
#include <efm8_usb.h>
#include "descriptors.h"
#include "rgb_led.h"

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Variables
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Functions
//-----------------------------------------------------------------------------

void USBD_SofCb(uint16_t sofNr) {
	if (sofNr == 1) {
		// turn on the blue LED so we know the fucking thing is alive.
		if (PCA0CPH1 == 255) {
			PCA0CPH1 = 0;
		} else if (PCA0CPH1 == 0) {
			PCA0CPH1 = 255;
		}
	}
}

uint16_t USBD_XferCompleteCb(uint8_t epAddr, USB_Status_TypeDef status,
		uint16_t xferred, uint16_t remaining) {
	UNREFERENCED_ARGUMENT(epAddr);
	UNREFERENCED_ARGUMENT(status);
	UNREFERENCED_ARGUMENT(xferred);
	UNREFERENCED_ARGUMENT(remaining);
	if (RGB_CEX_GREEN == 0) {
		RGB_CEX_GREEN = 255;
	} else if (RGB_CEX_GREEN == 255) {
		RGB_CEX_GREEN = 0;
	}
	P3_B4 = ~P3_B4;

	return 0;
}

