/*******************************************************************************
 * @file callback.c
 * @brief USB Callbacks.
 *******************************************************************************/

//=============================================================================
// src/callback.c: generated by Hardware Configurator
//
// This file is only generated if it does not exist. Modifications in this file
// will persist even if Configurator generates code. To refresh this file,
// you must first delete it and then regenerate code.
//=============================================================================
//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB2_Register_Enums.h>
#include <efm8_usb.h>
#include "descriptors.h"
#include "rgb_led.h"

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Variables
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Functions
//-----------------------------------------------------------------------------

void USBD_EnterHandler(void) {

}

void USBD_ExitHandler(void) {

}

void USBD_ResetCb(void) {

}

void USBD_SofCb(uint16_t sofNr) {
	static Color ledcolor = {0, 0, 0};
	static thisColor = 0; // 0 = red, 1 = green, 2 = blue

	switch (thisColor) {
	case 0 : if (255 == ledcolor.red) {
			ledcolor.red = 0;
			thisColor = 1;
		} else {
			++ledcolor.red;
		}
		break;
	case 1 : if (255 == ledcolor.green) {
			ledcolor.green = 0;
			thisColor = 2;
		} else {
			++ledcolor.green;
		}
		break;
	case 2 : if (255 == ledcolor.blue) {
			ledcolor.blue = 0;
			thisColor = 0;
		} else {
			++ledcolor.blue;
		}
		break;
	} // switch
	RGB_SetColor(ledcolor, 255);
}

void USBD_DeviceStateChangeCb(USBD_State_TypeDef oldState,
		USBD_State_TypeDef newState) {

}

bool USBD_IsSelfPoweredCb(void) {

	return true;
}

USB_Status_TypeDef USBD_SetupCmdCb(
		SI_VARIABLE_SEGMENT_POINTER(setup, USB_Setup_TypeDef, MEM_MODEL_SEG)) {
	USB_Status_TypeDef retVal = USB_STATUS_REQ_UNHANDLED;

	return retVal;
}

uint16_t USBD_XferCompleteCb(uint8_t epAddr, USB_Status_TypeDef status,
		uint16_t xferred, uint16_t remaining) {

	return 0;
}

