/*******************************************************************************
 * @file callback.c
 * @brief USB Callbacks.
 *******************************************************************************/

//=============================================================================
// src/callback.c: generated by Hardware Configurator
//
// This file is only generated if it does not exist. Modifications in this file
// will persist even if Configurator generates code. To refresh this file,
// you must first delete it and then regenerate code.
//=============================================================================
//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB2_Register_Enums.h>
#include <efm8_usb.h>
#include "descriptors.h"
#include "rgb_led.h"
#include "usb_midi.h"

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Variables
//-----------------------------------------------------------------------------
extern bit newIncomingPacket;
extern SI_SEGMENT_VARIABLE(EndpointBuffer, MIDI_Event_Packet_t, SI_SEG_XDATA);
extern SI_SEGMENT_VARIABLE(midiUsbOutPacket, MIDI_Event_Packet_t, SI_SEG_XDATA);


//-----------------------------------------------------------------------------
// Functions
//-----------------------------------------------------------------------------

void USBD_SofCb(uint16_t sofNr) {
	UNREFERENCED_ARGUMENT(sofNr);
	P3_B4 = ~P3_B4;
}

uint16_t USBD_XferCompleteCb(uint8_t epAddr, USB_Status_TypeDef status,
		uint16_t xferred, uint16_t remaining) {
	  UNREFERENCED_ARGUMENT(xferred);
	  UNREFERENCED_ARGUMENT(remaining);

	if (status == USB_STATUS_OK) {
		if (epAddr == 2) {
			// copy contents of the endpoint buffer to the
			// working buffer which will be parsed.
			midiUsbOutPacket.event = EndpointBuffer.event;
			midiUsbOutPacket.byte1 = EndpointBuffer.byte1;
			midiUsbOutPacket.byte2 = EndpointBuffer.byte2;
			midiUsbOutPacket.byte3 = EndpointBuffer.byte3;
			// tell the world we have a new packet.
			newIncomingPacket = 1;
			// prepare for the next message packet.
			USBD_Read(EP1OUT, (uint8_t *) &EndpointBuffer,
						sizeof(MIDI_Event_Packet_t), // midi messages are four bytes
						true); // we need the transfer-complete callback.
		}
	}
	return 0;
}

