//=========================================================
// src/EFM8-USB-MIDI_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB2_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
#include "efm8_usb.h"
// [Generated Includes]$
//#include "rgb_led.h"
#include "bsp.h"
#include "disp.h"
#include "render.h"
#include "tick.h"

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
	static SI_SEGMENT_VARIABLE(line[DISP_BUF_SIZE], uint8_t, RENDER_LINE_SEG);
	uint8_t y;
	uint16_t lastTick;
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

	// turn on the blue LED so we know the fucking thing is alive.
	PCA0CPH1 = 255;
	DISP_Init();
	lastTick = GetTickCount();

	for (y = 0; y < FONT_HEIGHT; y++) {
		RENDER_ClrLine (line);
		RENDER_StrLine(line, 3, y, "TEST");
		DISP_WriteLine(4 + y, line);
	}

	while (1) {
// $[Generated Run-time code]
// [Generated Run-time code]$
		for (y = 0; y < FONT_HEIGHT; y++) {
			RENDER_ClrLine (line);
			RENDER_StrLine(line, 3, y, "TEST");
			DISP_WriteLine(4 + y, line);
		}

	}
}
